{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Fuse API"
  },
  "basePath": "/fuse",
  "tags": [
    {
      "name": "fuse",
      "description": "\nEverything about Fuse Graph Engine."
    }
  ],
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json",
    "application/xml"
  ],
  "paths": {
    "/": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "Get API Info",
        "description": "API Info",
        "parameters": [],
        "responses": {
          "200": {
            "description": "API resources urls"
          }
        }
      }
    },
    "/idgen/init": {
      "get": {
        "tags": [
          "management"
        ],
        "summary": "Init DB id Sequencer",
        "description": "Initialize DB id Sequencer tables",
        "parameters": [
          {
            "name": "names",
            "in": "query",
            "description": "Sequence names [Entity,Relation,Evalue,Rvalue,workerId]  ",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SequenceNames"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Initiated"
          }
        }
      }
    },
    "/internal/version": {
      "get": {
        "tags": [
          "management"
        ],
        "summary": "Get server version",
        "description": "Server versions",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Server version"
          }
        }
      }
    },
    "/internal/config": {
      "get": {
        "tags": [
          "management"
        ],
        "summary": "Get server configurations (according to app.config)",
        "description": "Server configuration",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Server configuration"
          }
        }
      }
    },
    "/catalog/ontology": {
      "post": {
        "tags": [
          "catalog"
        ],
        "summary": "add an ontology to catalog",
        "description": "add an ontology to catalog",
        "parameters": [
          {
            "in": "body",
            "name": "<body>",
            "description": "Ontology",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Ontology"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Query summery with first page result data",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          }
        }
      },
      "get": {
        "tags": [
          "catalog"
        ],
        "summary": "Get all Ontology catalog resources",
        "description": "Ontology catalog resources",
        "parameters": [],
        "responses": {
          "200": {
            "description": "All Ontology "
          }
        }
      }
    },
    "/catalog/ontology/{id}": {
      "get": {
        "tags": [
          "catalog"
        ],
        "summary": "Get Ontology resource by name ",
        "description": "Ontology resource",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ontology name",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Ontology Json"
          }
        }
      }
    },
    "/catalog/ontology/{id}/schema": {
      "get": {
        "tags": [
          "catalog"
        ],
        "summary": "Get specific Ontology schema resource ",
        "description": "Ontology schema resource",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ontology name",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Ontology Json"
          }
        }
      }
    },
    "/query/cypher": {
      "post": {
        "tags": [
          "query"
        ],
        "summary": "submit a cypher query request",
        "description": "submit a query to the engine",
        "parameters": [
          {
            "in": "body",
            "name": "<body>",
            "description": "Cypher Query json request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CypherQueryRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Query summery with first page result data",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          }
        }
      }
    },
    "/query/cypher/run": {
      "get": {
        "tags": [
          "query"
        ],
        "summary": "submit & run cypher query directly  ",
        "description": "submit & run a query to the engine",
        "parameters": [
          {
            "name": "cypher",
            "in": "query",
            "description": "cypher query",
            "required": true,
            "type": "string",
            "default": "Match (e:Entity)-[hasEv:hasEvalue]->(v:Evalue) Where (v.fieldId = \"name\" AND v.stringValue = \"Napoleon\") Return *"
          },
          {
            "name": "ontology",
            "in": "query",
            "description": "ontology id",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Query summery with first page result data",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          }
        }
      }
    },
    "/query/v1": {
      "post": {
        "tags": [
          "query"
        ],
        "summary": "submit a (V1) query request",
        "description": "submit a query to the engine",
        "parameters": [
          {
            "in": "body",
            "name": "<body>",
            "description": "V1 Query json request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/QueryRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Query summery (HATEOAS Rest Specification).",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          }
        }
      }
    },
    "/query/v1/validate": {
      "post": {
        "tags": [
          "query"
        ],
        "summary": "submit & validate V1 query directly  ",
        "description": "submit & validate a query to the engine",
        "parameters": [
          {
            "in": "body",
            "name": "<body>",
            "description": "V1 Query json ",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Query"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Query validation summery ",
            "schema": {
              "$ref": "#/definitions/QueryValidation"
            }
          }
        }
      }
    },
    "/query/v1/plan": {
      "post": {
        "tags": [
          "plan"
        ],
        "summary": "submit V1 query and see generated plan ",
        "description": "submit V1 query and see generated plan ",
        "parameters": [
          {
            "in": "body",
            "name": "<body>",
            "description": "V1 Query json ",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Query"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Plan",
            "schema": {
              "$ref": "#/definitions/PlanInfo"
            }
          }
        }
      }
    },
    "/query/v1/traversal": {
      "post": {
        "tags": [
          "plan"
        ],
        "summary": "submit V1 query and see generated execution traversal gremlin ",
        "description": "submit V1 query and see generated execution traversal gremlin ",
        "parameters": [
          {
            "in": "body",
            "name": "<body>",
            "description": "V1 Query json ",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Query"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Traversal gremlin",
            "schema": {
              "$ref": "#/definitions/TraversalInfo"
            }
          }
        }
      }
    },
    "/query/v1/run": {
      "post": {
        "tags": [
          "query"
        ],
        "summary": "submit & run V1 query directly  ",
        "description": "submit & run a query to the engine",
        "parameters": [
          {
            "in": "body",
            "name": "<body>",
            "description": "V1 Query json ",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Query"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a Query summery with first page result data",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          }
        }
      }
    },
    "/query": {
      "get": {
        "tags": [
          "query"
        ],
        "summary": "Basic general query Info",
        "description": "Basic query Info",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Basic query Info",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/QueryInfo"
              }
            }
          }
        }
      }
    },
    "/query/{id}": {
      "get": {
        "tags": [
          "query"
        ],
        "summary": "Fetch query info by ID",
        "description": "Fetch query info by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns <code>200</code> with a single query info or <code>404</code>",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "query"
        ],
        "summary": "Deletes a query by ID",
        "description": "Deletes a query by ID.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "A <code>204</code>"
          }
        }
      }
    },
    "/query/{id}/plan/json": {
      "get": {
        "tags": [
          "plan"
        ],
        "summary": "Fetch query plan by query ID",
        "description": "Fetch query plan by query ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns <code>200</code> with a single query info or <code>404</code>",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/query/{id}/cursor": {
      "get": {
        "tags": [
          "cursor"
        ],
        "summary": "Fetch query info by ID",
        "description": "Fetch query info by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns <code>200</code> with a single query info or <code>404</code>",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "cursor"
        ],
        "summary": "Deletes a query by ID",
        "description": "Deletes a query by ID.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "A <code>204</code>"
          }
        }
      }
    },
    "/query/{id}/cursor/{cursorId}/page": {
      "get": {
        "tags": [
          "page"
        ],
        "summary": "Fetch query info by ID",
        "description": "Fetch query info by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "cursorId",
            "in": "path",
            "description": "cursor ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns <code>200</code> with a single query info or <code>404</code>",
            "schema": {
              "$ref": "#/definitions/QueryInfo"
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "page"
        ],
        "summary": "Deletes a query by ID",
        "description": "Deletes a query by ID.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "cursorId",
            "in": "path",
            "description": "cursor ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "A <code>204</code>"
          }
        }
      }
    },
    "/query/{id}/cursor/{cursorId}/page/{pageId}/data": {
      "get": {
        "tags": [
          "page"
        ],
        "summary": "Fetch Page data by id",
        "description": "Fetch Page data by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "cursorId",
            "in": "path",
            "description": "cursor ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "pageId",
            "in": "path",
            "description": "page ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns <code>200</code> with first page of data or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "page"
        ],
        "summary": "Deletes page data",
        "description": "Deletes page data by ID.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "cursorId",
            "in": "path",
            "description": "cursor ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "pageId",
            "in": "path",
            "description": "page ID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "A <code>204</code>"
          }
        }
      }
    },
    "/query/{id}/cursor/{cursorId}/page/{pageId}/format/{format}/data": {
      "get": {
        "tags": [
          "page"
        ],
        "summary": "Fetch Page data with format ",
        "description": "Fetch Page data with format ",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "query ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "cursorId",
            "in": "path",
            "description": "cursor ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "pageId",
            "in": "path",
            "description": "page ID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "format",
            "in": "path",
            "description": "data format",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns <code>200</code> with first page of data or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/dashboard/entities": {
      "get": {
        "tags": [
          "dashboard"
        ],
        "summary": "Show summery of DB existing entities",
        "description": "summery of DB entities",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> summery of db elements created (entities / properties) or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/dashboard/fields": {
      "get": {
        "tags": [
          "dashboard"
        ],
        "summary": "Show summery of DB existing fields types and histogram",
        "description": "summery of DB fields",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> summery of db fields types (histogram) or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/dashboard/created": {
      "get": {
        "tags": [
          "dashboard"
        ],
        "summary": "Show summery of created DB elements by creation time ",
        "description": "summery of time bases created DB elements ",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> Show summery of created DB elements by creation time  or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/dashboard/count": {
      "get": {
        "tags": [
          "dashboard"
        ],
        "summary": "Show summery of different server statistical metrics",
        "description": "summery server statistical metrics",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> Show summery of different server statistical metrics or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/load/ontology/{id}/init": {
      "get": {
        "tags": [
          "load"
        ],
        "summary": "Initialize (Drop & Create) E/S templates & Indices related to the ontology",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ontology ID.",
            "required": true,
            "type": "string"
          }
        ],
        "description": "Initialize (Drop & Create) E/S templates & Indices related to the ontology",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> number of indices created or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/load/ontology/{id}/drop": {
      "get": {
        "tags": [
          "load"
        ],
        "summary": "Drop E/S templates & Indices related to the ontology",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ontology ID.",
            "required": true,
            "type": "string"
          }
        ],
        "description": "Drop  E/S templates & Indices related to the ontology",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> number of indices dropped or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/load/ontology/{id}/load": {
      "post": {
        "tags": [
          "load"
        ],
        "summary": "Load Logical graph into DB according to specific ontology Transformer (see /catalog/ontology)",
        "parameters": [
          {
            "name": "directive",
            "in": "query",
            "description": "Directive [UPSERT/INSERT] ",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "description": "ontology ID.",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "<body>",
            "description": "Logical Graph",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LogicalGraph"
            }
          }
        ],
        "description": "Load Logical graph into DB according to specific ontology Transformer ",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> number of graph elements created or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/load/ontology/{id}/upload": {
      "post": {
        "tags": [
          "upload"
        ],
        "summary": "Upload json/zip File with Logical graph into DB according to specific ontology Transformer (see /catalog/ontology)",
        "consumes": ["multipart/form-data","application/x-www-form-urlencoded"],
        "parameters": [
          {
            "name": "directive",
            "in": "query",
            "description": "Directive [UPSERT/INSERT] ",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "description": "ontology ID.",
            "required": true,
            "type": "string"
          },
          {
            "in": "formData",
            "name": "file",
            "description": "file",
            "required": true,
            "type": "file"
          }
        ],
        "description": "Load Logical graph into DB according to specific ontology Transformer ",
        "responses": {
          "200": {
            "description": "Returns <code>200</code> number of graph elements created or <code>404</code>"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    }
  },
  "definitions": {
    "SequenceNames": {
      "type":"string",
      "example":"Entity,Relation,Evalue,Rvalue"
    },
    "Ontology": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "query": {
          "type": "string"
        }
      },
      "example":     {
        "ont": "LesMiserables",
        "entityTypes": [
          {
            "eType": "Person",
            "name": "Person",
            "metadata": [],
            "properties": [
              "id",
              "firstName",
              "lastName",
              "gender",
              "birthDate",
              "deathDate",
              "name"
            ]
          }
        ],
        "relationshipTypes": [
          {
            "rType": "know",
            "name": "know",
            "directional": true,
            "ePairs": [
              {
                "eTypeA": "Person",
                "eTypeB": "Person"
              }
            ],
            "metadata": [],
            "properties": [
              "id",
              "startDate"
            ]
          }
        ],
        "properties": [
          {
            "pType": "id",
            "name": "id",
            "type": "string"
          },
          {
            "pType": "firstName",
            "name": "firstName",
            "type": "string"
          },
          {
            "pType": "lastName",
            "name": "lastName",
            "type": "string"
          },
          {
            "pType": "gender",
            "name": "gender",
            "type": "string"
          },
          {
            "pType": "birthDate",
            "name": "birthDate",
            "type": "date"
          },
          {
            "pType": "deathDate",
            "name": "deathDate",
            "type": "string"
          },
          {
            "pType": "name",
            "name": "name",
            "type": "string"
          }
        ]
      }
    },
    "CypherQueryRequest": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "query": {
          "type": "string"
        }
      },
      "example": {
        "id": "1",
        "name": "Q1",
        "ontology": "Knowledge",
        "query": "match (e:Entity)-[hasEv:hasEvalue]->(v:Evalue), (e:Entity)-[hasRelEn:relatedEntity]->(e2:Entity) return *"
      }
    },
    "QueryRequest": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "query": {
          "$ref": "#/definitions/Query"
        },
        "createCursorRequest": {
          "$ref": "#/definitions/CreateCursorRequest"
        }
      },
      "example": {
        "id": "1",
        "name": "Q1",
        "query": {
          "ont": "Knowledge",
          "elements": [
            {
              "type": "Start",
              "eNum": 0,
              "next": 1
            },
            {
              "type": "ETyped",
              "eNum": 1,
              "next": 2,
              "eTag": "A",
              "eType": "Entity"
            },
            {
              "eNum": 2,
              "type": "Quant1",
              "qType": "all",
              "next": [
                3,
                5
              ]
            },
            {
              "type": "Rel",
              "dir": "R",
              "eNum": 3,
              "next": 4,
              "rType": "relatedEntity"
            },
            {
              "type": "ETyped",
              "eNum": 4,
              "eTag": "B",
              "eType": "Entity"
            },
            {
              "type": "Rel",
              "dir": "R",
              "eNum": 5,
              "next": 6,
              "rType": "hasEvalue"
            },
            {
              "type": "ETyped",
              "eNum": 6,
              "eTag": "Ev",
              "eType": "Evalue"
            }
          ]
        },
        "createCursorRequest": {
          "maxExecutionTime": 600000,
          "cursorType": "LogicalGraphCursorRequest",
          "format": "XML",
          "createPageRequest": {
            "pageSize": 100,
            "fetch": false
          },
          "include": "all"
        }
      }
    },
    "CreateCursorRequest": {
      "type": "object",
      "properties": {
        "maxExecutionTime": {
          "type": "integer",
          "format": "int32"
        },
        "cursorType": {
          "type": "string"
        },
        "include": {
          "type": "string"
        },
        "createPageRequest": {
          "$ref": "#/definitions/CreatePageRequest"
        }
      },
      "example": {
        "maxExecutionTime": 600000,
        "cursorType": "graph",
        "createPageRequest": {
          "pageSize": 100,
          "fetch": false
        },
        "include": "all"
      }
    },
    "CreatePageRequest": {
      "type": "object",
      "properties": {
        "pageSize": {
          "type": "integer",
          "format": "int32"
        },
        "fetch": {
          "type": "boolean"
        }
      },
      "example": {
        "pageSize": 100,
        "fetch": false
      }
    },
    "Query": {
      "type": "object",
      "properties": {
        "ont": {
          "type": "string"
        },
        "elements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Element"
          }
        }
      },
      "example": {
        "ont": "Knowledge",
        "elements": [
          {
            "type": "Start",
            "eNum": 0,
            "next": 1
          },
          {
            "type": "ETyped",
            "eNum": 1,
            "next": 2,
            "eTag": "A",
            "eType": "Entity"
          },
          {
            "eNum": 2,
            "type": "Quant1",
            "qType": "all",
            "next": [
              3,
              5
            ]
          },
          {
            "type": "Rel",
            "dir": "R",
            "eNum": 3,
            "next": 4,
            "rType": "relatedEntity"
          },
          {
            "type": "ETyped",
            "eNum": 4,
            "eTag": "B",
            "eType": "Entity"
          },
          {
            "type": "Rel",
            "dir": "R",
            "eNum": 5,
            "next": 6,
            "rType": "hasEvalue"
          },
          {
            "type": "ETyped",
            "eNum": 6,
            "eTag": "Ev",
            "eType": "Evalue"
          }
        ]
      }
    },
    "Element": {
      "type": "object",
      "properties": {
        "eNum": {
          "type": "integer",
          "format": "int32"
        },
        "type": {
          "type": "string"
        },
        "eTag": {
          "type": "string"
        },
        "eType": {
          "type": "string"
        },
        "eID": {
          "type": "string"
        }
      }
    },
    "QueryInfo": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "PlanInfo": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "TraversalInfo": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "QueryValidation": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "error": {
          "type": "string"
        }
      }
    },
    "LogicalGraph": {
      "type": "object",
      "properties": {
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LogicalNode"
          }
        },
        "edges": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LogicalEdge"
          }
        }
      },
      "example": {
        "nodes": [
          {
            "metadata": {
              "group": 1
            },
            "id": "Myriel",
            "label": "Person",
            "properties": {
              "sex": "female"
            }
          },
          {
            "metadata": {
              "group": 1
            },
            "id": "Napoleon",
            "label": "Person",
            "properties": {
              "name": "Napoleon_1",
              "sex": "male"
            }
          },
          {
            "metadata": {
              "group": 2
            },
            "id": "Mlle.Baptistine",
            "label": "Person",
            "properties": {
              "sex": "some..."
            }
          },
          {
            "metadata": {
              "group": 1
            },
            "id": "hezi",
            "label": "Person",
            "properties": {
              "name": "Hezi-markov"
            }
          },
          {
            "metadata": {
              "group": 1
            },
            "id": "moti",
            "label": "Person",
            "properties": {
              "name": "moti-moti"
            }
          }
        ],
        "edges": [
          {
            "label": "knows",
            "source": "hezi",
            "target": "Champtercier",
            "metadata": {
              "value": 1
            }
          },
          {
            "label": "knows",
            "source": "CountessdeLo",
            "target": "moti",
            "metadata": {
              "value": 8
            }
          },
          {
            "label": "knows",
            "source": "hezi",
            "target": "moti",
            "metadata": {
              "value": 10
            }
          }
        ]
      }
    },
    "LogicalEdge": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "target": {
          "type": "string"
        },
        "properties": {
          "$ref": "#/definitions/Properties"
        },
        "metadata": {
          "$ref": "#/definitions/Metadata"
        }
      }
    },
    "LogicalNode": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "properties": {
          "$ref": "#/definitions/Properties"
        },
        "metadata": {
          "$ref": "#/definitions/Metadata"
        }
      }
    },
    "Metadata": {
      "type": "object",
      "properties": {
        "anyOf": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "Properties": {
      "type": "object",
      "properties": {
        "anyOf": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "Property": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    }
  }
}
